# Generated by Django 3.1.3 on 2022-03-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media')),
                ('name', models.CharField(default='devesh', max_length=255)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('age', models.IntegerField(default=20)),
                ('filename', models.CharField(default='devesh', max_length=255)),
                ('user', models.CharField(default='devesh', max_length=255)),
                ('date', models.CharField(default='devesh', max_length=255)),
            ],
        ),
    ]
